# Generated by Django 3.1.2 on 2020-10-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=100)),
                ('cemail', models.EmailField(default='', max_length=254)),
                ('crollno', models.CharField(default='', max_length=50)),
                ('msg', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
